---
# See ../DEPENDENCIES.md for more information
name: Dependabot hack
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - never-trigger-this-dependabot-workflow

jobs:

  dependabot_hack:
    name: Ensure dependabot version checks
    runs-on: ubuntu-20.04
    steps:
      # update the version in these places manually when Dependabot changes it here:
      # 1. /ci/devtools.Dockerfile
      - uses: microsoft/vcpkg@2021.05.12
